# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='test',
            field=models.CharField(default='test', max_length=5),
            preserve_default=False,
        ),
    ]
