# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_timeline_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='test',
        ),
    ]
