# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_timeline_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
