# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170531_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='timeline',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
